### ISSUE TITLE
CraftAMap 导出器为啥输不了密钥

### ISSUE THREAD

**Issue by xiangzai233** [hyunel/CraftAMap-Exporter#1]
![image](https://user-images.githubusercontent.com/121146361/208819191-fdf6f70e-5192-49fe-8e6e-c5f44be59b32.png)
![image](https://user-images.githubusercontent.com/121146361/208819203-be7e68fa-2e6b-4705-9024-2e8b3ff6ff0d.png)

**Comment by hyunel** [comment]
不是web 服务，类型需要是JS API

**Comment by xiangzai233** [comment]
> 



> 不是web服务，类型需要是JS API

弄个教程qwq

**Comment by xiangzai233** [comment]
> 不是web 服务，类型需要是JS API
解决了:)
